FROM ubuntu:22.04

ARG DAPPER_HOST_ARCH
ENV HOST_ARCH=${DAPPER_HOST_ARCH} ARCH=${DAPPER_HOST_ARCH}

COPY sources.list /etc/apt/sources.list
RUN apt-get clean && apt-get update && \
    apt-get install -y \
        gcc \
        ca-certificates \
        git \
        wget \
        curl \
        vim \
        less \
        file && \
    rm -f /bin/sh && ln -s /bin/bash /bin/sh

ENV GOLANG_ARCH_amd64=amd64 GOLANG_ARCH_arm=arm64 GOLANG_ARCH=GOLANG_ARCH_${ARCH} \
    GOPATH=/go PATH=/go/bin:/usr/local/go/bin:${PATH} SHELL=/bin/bash
RUN wget -O - https://go.dev/dl/go1.19.linux-${!GOLANG_ARCH}.tar.gz | tar -xzf - -C /usr/local

ENV DOCKER_VERSION=20.10.24
RUN if [ "${ARCH}" = "amd64" ]; then \
        wget -O - https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VERSION}.tgz | tar -xzf - -C /usr/local/bin --strip-components=1 docker/docker; \
    elif [ "${ARCH}" = "arm" ]; then \
        wget -O - https://download.docker.com/linux/static/stable/aarch64/docker-${DOCKER_VERSION}.tgz | tar -xzf - -C /usr/local/bin --strip-components=1 docker/docker; \
    fi && \
    chmod +x /usr/local/bin/docker

ENV DAPPER_ENV REPO TAG DRONE_TAG
ENV DAPPER_SOURCE /go/src/github.com/AliyunContainerService/docker-machine-driver-aliyunecs/
ENV DAPPER_OUTPUT ./bin ./dist
ENV DAPPER_DOCKER_SOCKET true
ENV TRASH_CACHE ${DAPPER_SOURCE}/.trash-cache
ENV HOME ${DAPPER_SOURCE}
WORKDIR ${DAPPER_SOURCE}

ENTRYPOINT ["./scripts/entry"]
CMD ["ci"]